posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.list_posts, name='index'),
    path('search/', views.search_posts, name='search'),
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/', views.detail_post, name='detail'),
    path('update/<int:post_id>/', views.update_post, name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('categories/<int:category_id>', views.detail_category, name='detail_category'),
]

postsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=255, default="Título Padrão")
    text = models.CharField(max_length=255)
    date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return f'{self.title} - ({self.text}) - ({self.date}) - ({self.author.username})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" -({self.date}) - {self.author.username}'
    

class Category(models.Model):
    title = models.CharField(max_length=255)
    text = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'"{self.title}" -{self.text}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import *

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'author',
            'title',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'title': 'Título',
            'text': 'Conteúdo',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Conteúdo',
        }



class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = [
            'title',
            'text',
            'posts',
        ]
        labels = {
            'title': 'Título',
            'text': 'Descrição',
            'posts': 'Posts',
        }

posts/views.py
from django.http import HttpResponseRedirect
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.urls import reverse
from .temp_data import post_data
from django.shortcuts import render
from .models import *
from django.shortcuts import render, get_object_or_404
from datetime import datetime
from django.contrib.auth.models import User
from django.views import generic
from django.urls import reverse_lazy
from .forms import *
from django.utils import timezone


def detail_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_data = Comment.objects.filter(post=post_id)
    context = {'post': post,  'comment_list':reversed(comment_data)}
    return render(request, 'posts/detail.html', context)


def list_posts(request):
    post_list = Post.objects.all()
    context = {"post_list": post_list}
    return render(request, 'posts/index.html', context)


def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(text__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'posts/search.html', context)


def create_post(request):
    if request.method == 'POST':
        post_title = request.POST['title']
        post_text = request.POST['text']
        author_id = request.POST['author']
        post_author = User.objects.get(id=author_id)
        post = Post(author = post_author, title=post_title, text=post_text,
                      date = datetime.now())
        post.save()
        return HttpResponseRedirect(
            reverse('posts:detail', args=(post.id, )))
    else:
        form = PostForm()
        context = {'form': form}
        return render(request, 'posts/create.html', context)


def update_post(request, post_id):

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = Post.objects.get(id=post_id)
            post.title = request.POST['title']
            post.date = datetime.now()
            post.text = request.POST['text']

            post.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post.id, )))

    else:
        form = PostForm()
        context = {'form': form}
        return render(request, 'posts/update.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('posts:index'))

    context = {'post': post}
    return render(request, 'posts/delete.html', context)


def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post, date = datetime.now())
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/categories.html'

def detail_category(request, category_id):  
    category = get_object_or_404(Category, pk=category_id)
    post_list = Post.objects.filter(category=category_id)
    context = {'category': category,  'post_list': post_list}
    return render(request, 'posts/detail_category.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


posts/templates/posts/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Listas de categorias</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <h3> <a href="{% url 'posts:detail_category' category.id %}"> {{category.title}}  </a>   </h3>
        </header>
        <p>Descrição dessa categoria: {{category.text}}   </p>
        <div class="lista-de-cards">
            {% for post in category.posts.all %}
            <div class="card">
                <a href="{% url 'posts:detail' post.id %}"> {{ post.title }}   </a>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

</section>

{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Fazer comentário sobre o Post {{ post.title }} postado em {{ post.date }}</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentário</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Escreva seu Post</h2>
<p>Comprou um barco novo? Fez um tempo melhor no ergômetro? Ganhou da medicina? Comente!</p>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    
    {{ form.as_p }} 
    
    
    <!-- <p>
        <label for="id_author">Insira o seu usuário:</label>
        <input type="text" name="author" id="id_author" />
    </p>

    <p>
        <label for="id_title">Insira o título da sua postagem:</label>
        <input type="text" name="title" id="id_title" />
    </p>
    <p>
        <label for="id_text">Insira o conteúdo da sua postagem:</label>
        <input type="text" name="text" id="id_text" />
    </p> -->






    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja apagar o post de título '{{ post.title }}' feito em {{ post.date }}?
  </p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }} ({{ post.date }})
{% endblock title %}

{% block content %}
<h2>Detalhes do Post</h2>

<section class="dados-de-post">
    <ul>
        <li>Título: {{ post.title }}</li>
        <li>Data de publicação: {{ post.date }} </li>
        <li>Conteúdo: {{ post.text }} </li>
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>
</section>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if comment_list %}
            {% for comment in comment_list%}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <p>Postado em {{ comment.date |date:"F d, Y H:i" }} </p>
                    <figcaption>—{{ comment.author }}</figcaption>
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para esse post.</p>
        {% endif %}
    </ul>
</section>

<hr>

<a href="{% url 'posts:comment' post.pk %}"><button>Crie seu comentário</button></a>

<hr>

{% if post.category_set.all %}
    <li>Incluso nas categorias:
        {% for category in post.category_set.all %}
        <a href="{% url 'posts:detail_category' category.id %}"> {{category.title}}  </a> {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </li>

{% else %}
<p>Seu post não faz parte de nenhuma categoria ainda.</p>

{% endif %}

{% endblock content %}

posts/templates/posts/detail_category.html
{% extends 'base.html' %}

{% block title %}
{{category.title}}
{% endblock title %}

{% block content %}

<section>
    <hr>
    <article>
        <header>
            <h3> <a href="{% url 'posts:detail_category' category.id %}"> {{category.title}}  </a>   </h3>
        </header>
        <p>Descrição dessa categoria: {{category.text}}   </p>
        Posts pertencentes a essa categoria:
        <ul>
            {% for post in category.posts.all %}
            <li> <a href="{% url 'posts:detail' post.id %}"> {{ post.title }}   </a> </li>
            {% endfor %}
        </ul>
        </div>
    </article>

</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos as melhores postagens de remo estão aqui!</h2>
<section>
    <p>Quer buscar algo mais específico? <a href="{% url 'posts:search' %}">Buscar</a></p>
    <p>Quer postar sobre sua vitória? <a href="{% url 'posts:create' %}">Fazer um post</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' post.id %}"> {{ post.title }}   </a>
        <p>{{ post.text }}</p>
        <p>{{ post.date }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de posts por palavras presentes em seu conteúdo</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Pesquisa:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' post.id %}"> {{ post.title }}  </a>
        <p>({{ post.text }}) ({{ post.date }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block content %}
<h2>Atualizar Dados do Post</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <!-- <p>
    <label for="id_title">Título:</label>
    <input type="text" name="title" id="id_title" value="{{ post.title }}" />
  </p>
  <p>
    <label for=" id_text">Conteúdo:</label>
    <input
      type="text"
      name="text"
      id="id_text"
      value="{{ post.text }}"
    />
  </p> -->

  <button type="submit">Atualizar</button>
</form>
{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><b>PROA: O Blog de Remo</b></h1>
<p>Bem vindo ao melhor site para a comunidade remadora!</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | PROA!
    </title>
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <p>Início</p> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Posts</a></li>
                <li><a href="{% url 'posts:categories' %}">Categorias</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright Me 2023</small>
        </p>
    </footer>
</body>

</html>